env/values.tmpl.yaml

Reverts arcalos-management/environment-arcalos-prod-mgmt-dev#3

Revert "fix: second attempt to disable chartmuseum ingress"

---

env/requirements.yaml

fix: bump jx-app-sso to 0.0.29

---

systems/acme/templates/cert-manager-prod-issuer.yaml
systems/acme/templates/cert-manager-staging-issuer.yaml

fix: use additionalSolvers projectID value for DNS zone

---

env/templates/700-dex-ing.yaml

fix: correct path to tls production boolean

---

env/templates/700-jxui-ing.yaml

fix: remove arcalos name from jxui ingress

---

env/jx-app-sso/values.tmpl.yaml

fix: prevent exposecontroller coming to the party

---

env/jx-app-sso/values.tmpl.yaml
env/values.tmpl.yaml

chore: attempt to disable exposecontroller

---

env/templates/700-jxui-ing.yaml

fix: rename ingress so that sso finds the redirectURL

---

env/requirements.yaml

chore: update tenant-service and lighthotel

---

env/templates/arcalos-alpha-prod-secret.yaml

chore: added arcalos-alpha-prod-secret

---

env/templates/arcalos-scheduler.yaml
env/values.tmpl.yaml

fix: configuration to prevent arcalos builds

---

env/lighthouse-githubapp/values.tmpl.yaml

chore: enabled debug for lighthouse-githubapp

---

env/lighthouse-githubapp/values.tmpl.yaml

fix: set jx-tenant-service url value for ligthouse-githubapp

---

env/jx-tenant-service/values.tmpl.yaml
env/lighthouse-githubapp/values.tmpl.yaml

chore: use new private-key for lighthouse-githubapp

---

env/lighthouse-githubapp/values.tmpl.yaml

fix: enable extra go-scm logging

---

env/jx-tenant-service/values.tmpl.yaml
env/lighthouse-githubapp/values.tmpl.yaml

chore: revert back to original secrets for lighthouse-githubapp and tenant-service

---

env/lighthouse-githubapp/values.tmpl.yaml

chore: remove webhook logging for lighthouse-githubapp

---

env/oauth-proxy-jxui-frontend/values.tmpl.yaml
env/requirements.yaml

chore: adding oauth2-proxy

---

env/templates/700-dex-ing.yaml

chore: test if oauth2-proxy works using the dex ingress temporarily

---

env/oauth-proxy-jxui-frontend/values.tmpl.yaml
env/templates/700-jxui-ing.yaml

fix: add further oauth-proxy configuration

---

env/templates/700-jx-tenant-service-ing.yaml
env/templates/701-boot-tenant-service-ing.yaml

Signed-off-by: Mark Cox <markcox20@hotmail.com>

chore: allow hmac api in ing

---

env/oauth-proxy-jxui-backend/values.tmpl.yaml
env/oauth-proxy-jxui-frontend/values.tmpl.yaml

Reverts arcalos-management/environment-arcalos-prod-mgmt-dev#306

Revert "fix: remove the need to reference custom image for oauth proxy"

---

dependency-matrix/matrix.md
dependency-matrix/matrix.yaml
env/requirements.yaml

Reverts arcalos-management/environment-arcalos-prod-mgmt-dev#379

Revert "chore(deps): bump https://github.com/cloudbees/jxui-frontend from 0.0.1184 to 0.0.1185"

---

env/templates/700-jx-tenant-service-ing.yaml
env/templates/701-boot-tenant-service-ing.yaml

#https://github.com/cloudbees/arcalos/issues/945

chore: add workspace endpoint to ing

---

env/jxui-arcalos/values.tmpl.yaml
env/oauth-proxy-jxui-frontend/values.tmpl.yaml

contributes towards https://github.com/cloudbees/jxui-frontend/issues/1367

feat: enable sign out functionality

---

env/jx-tenant-service/values.tmpl.yaml

chore: update to new app name
